"use client";

import { useEffect, useMemo, useState } from "react";

type Order = { id: string; reference: string; school_name: string; contact_name: string; phone: string; total_kobo: number; payment_status: string; supply_status: string; created_at: string; };
type Customer = { school: string; contact: string; phone: string; orderCount: number; totalKobo: number; lastOrder: string; lastPayment: string; lastSupply: string; };
function naira(kobo: number) { return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(kobo / 100); }

export default function CustomerHistoryPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/customer-history", { cache: "no-store" }).then(async r => { const b = await r.json() as {orders?:Order[];error?:string}; if (!r.ok) throw new Error(b.error ?? "Unable to load customer history."); setOrders(b.orders ?? []); }).catch(e => setMessage(e instanceof Error ? e.message : "Unable to load customer history.")).finally(() => setLoading(false)); }, []);
  const customers = useMemo<Customer[]>(() => { const map = new Map<string,Customer>(); for (const o of orders) { const key = o.school_name.trim().toLowerCase()+"|"+o.phone.trim(); const x=map.get(key); if(x){x.orderCount++;x.totalKobo+=o.total_kobo;if(new Date(o.created_at)>new Date(x.lastOrder)){x.lastOrder=o.created_at;x.lastPayment=o.payment_status;x.lastSupply=o.supply_status;}} else map.set(key,{school:o.school_name,contact:o.contact_name,phone:o.phone,orderCount:1,totalKobo:o.total_kobo,lastOrder:o.created_at,lastPayment:o.payment_status,lastSupply:o.supply_status}); } return Array.from(map.values()); },[orders]);
  const visible=customers.filter(c => (c.school+" "+c.contact+" "+c.phone).toLowerCase().includes(search.toLowerCase()));
  return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-6xl px-6 py-8 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-slate-500">PUPILS START · Customers</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Customer History</h1><p className="mt-2 text-sm text-slate-600">Read-only history from existing orders.</p><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search school, contact, or phone" className="mt-6 w-full max-w-xl rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"/>{message&&<div className="mt-5 rounded-lg border border-red-200 bg-white px-4 py-3 text-sm text-red-700">{message}</div>}{loading?<p className="mt-8 text-sm text-slate-500">Loading customer history...</p>:visible.length===0?<div className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">No customers found.</div>:<div className="mt-8 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50"><tr><th className="sticky left-0 bg-slate-50 px-4 py-3 font-semibold">School</th><th className="px-4 py-3 font-semibold">Contact</th><th className="px-4 py-3 font-semibold">Phone</th><th className="px-4 py-3 font-semibold">Orders</th><th className="px-4 py-3 font-semibold">Total</th><th className="px-4 py-3 font-semibold">Last Order</th><th className="px-4 py-3 font-semibold">Payment</th><th className="px-4 py-3 font-semibold">Supply</th></tr></thead><tbody className="divide-y divide-slate-200">{visible.map(c=><tr key={c.school+"|"+c.phone}><td className="sticky left-0 bg-white px-4 py-3 font-medium">{c.school}</td><td className="px-4 py-3">{c.contact}</td><td className="px-4 py-3">{c.phone}</td><td className="px-4 py-3">{c.orderCount}</td><td className="px-4 py-3 font-medium">{naira(c.totalKobo)}</td><td className="px-4 py-3">{new Date(c.lastOrder).toLocaleDateString("en-NG")}</td><td className="px-4 py-3">{c.lastPayment}</td><td className="px-4 py-3">{c.lastSupply}</td></tr>)}</tbody></table></div>}</div></main>;
}
